/** English name of a currency's 1/100 (or common) subunit for amount-in-words. */
export function currencyMinorUnitEn(currencyCode: string | null | undefined, count: number): string {
  const code = String(currencyCode || "").trim().toUpperCase();
  const n = Number(count) || 0;
  if (!code) return "Paisa";
  const pair = MINOR_UNITS[code] || DEFAULT_CENT;
  return n === 1 ? pair[0] : pair[1];
}

const DEFAULT_CENT: [string, string] = ["Cent", "Cents"];

/** [singular, plural] — ISO 4217 common spoken subunits. Unknown codes use Cent/Cents. */
const MINOR_UNITS: Record<string, [string, string]> = {
  INR: ["Paisa", "Paisa"],
  NPR: ["Paisa", "Paisa"],
  PKR: ["Paisa", "Paisa"],
  BDT: ["Poisha", "Poisha"],
  BTN: ["Chetrum", "Chetrum"],
  MVR: ["Laari", "Laari"],
  LKR: ["Cent", "Cents"],
  USD: ["Cent", "Cents"],
  CAD: ["Cent", "Cents"],
  AUD: ["Cent", "Cents"],
  NZD: ["Cent", "Cents"],
  SGD: ["Cent", "Cents"],
  HKD: ["Cent", "Cents"],
  TWD: ["Cent", "Cents"],
  EUR: ["Cent", "Cents"],
  ZAR: ["Cent", "Cents"],
  KES: ["Cent", "Cents"],
  UGX: ["Cent", "Cents"],
  TZS: ["Cent", "Cents"],
  GBP: ["Penny", "Pence"],
  EGP: ["Piastre", "Piastres"],
  AED: ["Fils", "Fils"],
  BHD: ["Fils", "Fils"],
  KWD: ["Fils", "Fils"],
  JOD: ["Piastre", "Piastres"],
  OMR: ["Baisa", "Baisa"],
  QAR: ["Dirham", "Dirhams"],
  SAR: ["Halala", "Halalas"],
  CHF: ["Rappen", "Rappen"],
  THB: ["Satang", "Satang"],
  MYR: ["Sen", "Sen"],
  IDR: ["Sen", "Sen"],
  PHP: ["Sentimo", "Sentimos"],
  VND: ["Xu", "Xu"],
  JPY: ["Sen", "Sen"],
  KRW: ["Jeon", "Jeon"],
  CNY: ["Fen", "Fen"],
  MXN: ["Centavo", "Centavos"],
  BRL: ["Centavo", "Centavos"],
  ARS: ["Centavo", "Centavos"],
  COP: ["Centavo", "Centavos"],
  CLP: ["Centavo", "Centavos"],
  PEN: ["Centimo", "Centimos"],
  UYU: ["Centesimo", "Centesimos"],
  RUB: ["Kopek", "Kopeks"],
  UAH: ["Kopiyka", "Kopiyky"],
  BYN: ["Kopek", "Kopeks"],
  PLN: ["Grosz", "Groszy"],
  CZK: ["Heller", "Hellers"],
  HUF: ["Filler", "Fillers"],
  SEK: ["Ore", "Ore"],
  NOK: ["Ore", "Ore"],
  DKK: ["Ore", "Ore"],
  ISK: ["Eyrir", "Aurar"],
  TRY: ["Kurus", "Kurus"],
  ILS: ["Agora", "Agorot"],
  NGN: ["Kobo", "Kobo"],
  GHS: ["Pesewa", "Pesewas"],
  MAD: ["Centime", "Centimes"],
  TND: ["Millime", "Millimes"],
  AFN: ["Pul", "Puls"],
  ALL: ["Qindarka", "Qindarka"],
  DZD: ["Santeem", "Santeems"],
  AOA: ["Centimo", "Centimos"],
  AMD: ["Luma", "Luma"],
  AZN: ["Qapik", "Qapiks"],
  BGN: ["Stotinka", "Stotinki"],
  BAM: ["Fening", "Fening"],
  HRK: ["Lipa", "Lipa"],
  MKD: ["Deni", "Deni"],
  RSD: ["Para", "Para"],
  GEL: ["Tetri", "Tetri"],
  KZT: ["Tiyn", "Tiyn"],
  UZS: ["Tiyin", "Tiyin"],
  KGS: ["Tyiyn", "Tyiyn"],
  TJS: ["Diram", "Diram"],
  TMT: ["Tennesi", "Tennesi"],
  MNT: ["Mongo", "Mongo"],
  LAK: ["Att", "Att"],
  KHR: ["Sen", "Sen"],
  MMK: ["Pya", "Pyas"],
  BND: ["Cent", "Cents"],
  FJD: ["Cent", "Cents"],
  PGK: ["Toea", "Toea"],
  WST: ["Sene", "Sene"],
  TOP: ["Seniti", "Seniti"],
  SBD: ["Cent", "Cents"],
  VUV: ["Cent", "Cents"],
  XPF: ["Centime", "Centimes"],
  XOF: ["Centime", "Centimes"],
  XAF: ["Centime", "Centimes"],
  XCD: ["Cent", "Cents"],
  JMD: ["Cent", "Cents"],
  TTD: ["Cent", "Cents"],
  BBD: ["Cent", "Cents"],
  BSD: ["Cent", "Cents"],
  BZD: ["Cent", "Cents"],
  GYD: ["Cent", "Cents"],
  HTG: ["Centime", "Centimes"],
  DOP: ["Centavo", "Centavos"],
  CUP: ["Centavo", "Centavos"],
  CRC: ["Centimo", "Centimos"],
  GTQ: ["Centavo", "Centavos"],
  HNL: ["Centavo", "Centavos"],
  NIO: ["Centavo", "Centavos"],
  PAB: ["Centesimo", "Centesimos"],
  PYG: ["Centimo", "Centimos"],
  BOB: ["Centavo", "Centavos"],
  VES: ["Centimo", "Centimos"],
  ETB: ["Santim", "Santims"],
  MUR: ["Cent", "Cents"],
  SCR: ["Cent", "Cents"],
  SZL: ["Cent", "Cents"],
  LSL: ["Sente", "Lisente"],
  NAD: ["Cent", "Cents"],
  BWP: ["Thebe", "Thebe"],
  MWK: ["Tambala", "Tambala"],
  ZMW: ["Ngwee", "Ngwee"],
  MZN: ["Centavo", "Centavos"],
  MGA: ["Iraimbilanja", "Iraimbilanja"],
  KMF: ["Centime", "Centimes"],
  DJF: ["Centime", "Centimes"],
  RWF: ["Centime", "Centimes"],
  BIF: ["Centime", "Centimes"],
  SOS: ["Cent", "Cents"],
  SDG: ["Piastre", "Piastres"],
  SSP: ["Piastre", "Piastres"],
  LYD: ["Dirham", "Dirhams"],
  IQD: ["Fils", "Fils"],
  IRR: ["Rial", "Rials"],
  YER: ["Fils", "Fils"],
  LBP: ["Piastre", "Piastres"],
  SYP: ["Piastre", "Piastres"],
};
